import { TestResultSummary } from "./ReportBuilder.js";

export class HtmlTemplate {
    static generate(summary: TestResultSummary): string {
        const total = summary.passed + summary.failed + summary.skipped;
        const passRate = total > 0 ? ((summary.passed / total) * 100).toFixed(2) : "0";

        return `
        <html>
            <body style="font-family: Arial, sans-serif; padding: 20px;">
                <h2 style="color: #333;">Playwright UI Automation Report</h2>
                <div style="background: #f4f4f4; padding: 15px; border-radius: 5px; margin-bottom: 20px;">
                    <table style="width: 100%; text-align: left;">
                        <tr><th style="width: 100px;">Environment:</th><td>Stage</td></tr>
                        <tr><th>Browser:</th><td>Chromium / WebKit</td></tr>
                        <tr><th>Duration:</th><td>${summary.duration.toFixed(2)}s</td></tr>
                        <tr><th>Total Tests:</th><td>${total}</td></tr>
                        <tr><th>Pass Rate:</th><td><b>${passRate}%</b></td></tr>
                    </table>
                </div>

                <table style="border-collapse: collapse; width: 300px; margin-bottom: 20px;">
                    <tr style="background: #e6ffe6; color: #006600;">
                        <td style="padding: 8px; border: 1px solid #ccc;"><b>Passed</b></td>
                        <td style="padding: 8px; border: 1px solid #ccc; text-align: right;">${summary.passed}</td>
                    </tr>
                    <tr style="background: #ffe6e6; color: #cc0000;">
                        <td style="padding: 8px; border: 1px solid #ccc;"><b>Failed</b></td>
                        <td style="padding: 8px; border: 1px solid #ccc; text-align: right;">${summary.failed}</td>
                    </tr>
                    <tr style="background: #f9f9f9; color: #666;">
                        <td style="padding: 8px; border: 1px solid #ccc;"><b>Skipped</b></td>
                        <td style="padding: 8px; border: 1px solid #ccc; text-align: right;">${summary.skipped}</td>
                    </tr>
                </table>

                ${summary.failedTests.length > 0 ? `
                <h3 style="color: #cc0000;">Failed Tests</h3>
                <ul>
                    ${summary.failedTests.map((t: any) => `
                    <li style="margin-bottom: 10px;">
                        <b>&#10060; ${t.name}</b>
                        <br>
                        <span style="color: #555; font-size: 0.9em; white-space: pre-wrap;">${this.truncateMessage(t.failureMessage)}</span>
                    </li>
                    `).join("")}
                </ul>
                ` : '<h3 style="color: #006600;">🎉 All tests passed successfully!</h3>'}
                
                <br>
                <hr style="border: 0; border-top: 1px solid #eee;">
                <p style="color: #888; font-size: 0.8em;">This is an automated message generated by the Playwright Framework.</p>
            </body>
        </html>
        `;
    }

    private static truncateMessage(msg: string, length: number = 300): string {
        if (!msg) return "Unknown failure reason.";
        const clean = msg.replace(/[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g, '');
        return clean.length > length ? clean.substring(0, length) + "..." : clean;
    }
}
